version: "3.9"
services:
  moyu-web:
    build: .
    image: 3651809/moyu-web:latest
    container_name: moyu-web
    ports:
      - "3636:3636"
    restart: unless-stopped
    # 从宿主机加载.env文件
    volumes:
      - ./backend/.env:/app/backend/.env:ro
